### PR TITLE
update to latest version. also update dependencies

### PR DESCRIPTION
**Pull request by thht**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thht** [comment]
@conda-forge-admin, please rerender

**Comment by thht** [comment]
@larsoner and  @hoechenberger pymatreader just got a quite massive update under the hood.

* It is now build with modern tools
* it's fully typed (also internally)
* it works now with numpy 2
* The minimum required python version is now 3.9

I have checked that the eeglab and fieldtrip tests of mne still work with the latest version.

Because the changes are quite back and a problem with pymatreader in conda-forge would have effects on mne, could you give the PR a quick glance, please?

**Comment by thht** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
> Because the changes are quite back and a problem with pymatreader in conda-forge would have effects on mne, could you give the PR a quick glance, please?

Thanks for the heads up! I also added https://github.com/mne-tools/mne-python/pull/12770 to build against pymatreader `master` in the `pip-pre` MNE-Python job and looks like everything is okay!

**Pull request merged**
